const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Flash,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.ScriptsInEvents.Ejogo_Event22_Act4,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{Tilemap: 0},
	{Janela: 0},
	{Solid: 0},
	{Platform: 0},
	{Caixa: 0},
	{Porta: 0},
	{Chave: 0},
	{Bomba: 0},
	{ScrollTo: 0},
	{Jogador: 0},
	{Sensor_Solido: 0},
	{Suporte: 0},
	{Keyboard: 0},
	{Direcao: 0},
	{Flash: 0},
	{Porco_Patrulheiro: 0},
	{Sensor_Patrulheiro_Direita: 0},
	{Sensor_Patrulheiro_Esquerda: 0},
	{Vida_HUD: 0},
	{SpriteFont: 0},
	{Audio: 0},
	{Porco_Patrulheiro2: 0},
	{Espinho: 0},
	{Tilemap2: 0},
	{Batalha_dos_Porcos: 0},
	{Jogar: 0},
	{Porco_TelaStart: 0},
	{Historia: 0},
	{Jogador_TelaStart: 0},
	{Mouse: 0},
	{Tilemap3: 0},
	{Fundo_Dialogo: 0},
	{Cabeca_Jogador: 0},
	{SpriteFont2: 0},
	{Tilemap4: 0},
	{GameOver: 0},
	{TentarNovamente: 0},
	{Sim: 0},
	{Nao: 0},
	{Jogador_GameOver: 0},
	{Voltar: 0},
	{Vidas: 0}
];

self.InstanceType = {
	Tilemap: class extends self.ITilemapInstance {},
	Janela: class extends self.ISpriteInstance {},
	Caixa: class extends self.ISpriteInstance {},
	Porta: class extends self.ISpriteInstance {},
	Jogador: class extends self.ISpriteInstance {},
	Sensor_Solido: class extends self.ISpriteInstance {},
	Suporte: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Porco_Patrulheiro: class extends self.ISpriteInstance {},
	Sensor_Patrulheiro_Direita: class extends self.ISpriteInstance {},
	Sensor_Patrulheiro_Esquerda: class extends self.ISpriteInstance {},
	Vida_HUD: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Audio: class extends self.IInstance {},
	Porco_Patrulheiro2: class extends self.ISpriteInstance {},
	Espinho: class extends self.ISpriteInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	Batalha_dos_Porcos: class extends self.ISpriteFontInstance {},
	Jogar: class extends self.ISpriteFontInstance {},
	Porco_TelaStart: class extends self.ISpriteInstance {},
	Historia: class extends self.ISpriteFontInstance {},
	Jogador_TelaStart: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Tilemap3: class extends self.ITilemapInstance {},
	Fundo_Dialogo: class extends self.ISpriteInstance {},
	Cabeca_Jogador: class extends self.ISpriteInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	Tilemap4: class extends self.ITilemapInstance {},
	GameOver: class extends self.ISpriteFontInstance {},
	TentarNovamente: class extends self.ISpriteFontInstance {},
	Sim: class extends self.ISpriteFontInstance {},
	Nao: class extends self.ISpriteFontInstance {},
	Jogador_GameOver: class extends self.ISpriteInstance {},
	Voltar: class extends self.ISpriteFontInstance {}
}